### ISSUE TITLE
TypeError at /nexus/ 'type' object is not iterable

### ISSUE THREAD

**Issue by AndersenTobias** [disqus/gutter-django#11]
`nexus.autodiscover()` fails when trying to register `gutter.django` at the following line with `Django 1.6.10` (I suspect 1.6 is not supported, can someone confirm?)

`/usr/local/lib/python2.6/dist-packages/nexus/nexus_modules.py in make_admin_module`

```
new_site.register(model, make_nexus_model_admin(admin)) 
```

With error

```
TypeError at /nexus/
'type' object is not iterable
```

**Comment by AndersenTobias** [comment]
@dcramer ping

**Comment by kalail** [comment]
lol

**Comment by dcramer** [comment]
Nexus is (more or less) no longer maintained and I'm not involved in this project

**Comment by NorthIsUp** [comment]
I'm working on a non-nexus version for reasons such as this.

**Comment by AndersenTobias** [comment]
@dcramer Oh, sorry. Thanks for the info.
@NorthIsUp Cool. Are you working in this repo or are you forking it?

**Comment by AndersenTobias** [comment]
@NorthIsUp how is it going?

**Comment by mattrobenolt** [comment]
@AndersenTobias Pull requests accepted. In the meantime, this project is mostly used for us internally and I wouldn't really claim that it's ready for the public.

So if you have issues, feel free to submit patches, but things that don't affect us aren't our top priority for fixing.

Nor do we use Django 1.6 yet.
